### ISSUE TITLE
about time

### ISSUE THREAD

**Issue by SuQiANQAQ** [instavictor/alfred-omnifocus#1]
How can I get some hints about input times？
If I want to write 13.40 two days later, how do I write it？
What if I wanted to write 13.40 on the 27th？
Thanks alot

**Comment by instavictor** [comment]
Hi @SuQiANQAQ,

> If I want to write 13.40 two days later, how do I write it？

If today is Saturday, "two days later" will be Monday.
```
todo some stuff @Monday at 13.40
```

> What if I wanted to write 13.40 on the 27th？

```
todo some stuff @August 27 at 13.40
```

**Comment by instavictor** [comment]
I will close this issue.  I added these examples to the README.  Please don't hesitate to open another issue if you have any more questions or comments. Thanks!
